### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by glerchundi** [just-containers/s6-overlay-builder#12]
We need to create a good README to help people identifying:
- why this project exists
- what it includes
- how should be used
- make references to our 'recommended' base images.
  - just-containers/base (ubuntu trusty)
  - just-containers/base-slim (alpine)

**Comment by dreamcat4** [comment]
FYI
It's worth to use 'npm install doctoc && doctoc .' to automatically create
a good TOC in the github markdown files.

**Comment by glerchundi** [comment]
thanks!

**Comment by pikeas** [comment]
+1, would really love to see an explanation of how these bits fit together, especially the env variables.

**Comment by glerchundi** [comment]
closing this issue, we'll add documentation incrementally, I'll write something about envvars during this weekend.

**Comment by glerchundi** [comment]
@pikeas @dreamcat4 some notes about how env variables work were added :-)

**Comment by dreamcat4** [comment]
Thanks Gorka @glerchundi. May I make some comments / suggestions about the docs?

* Rename 'FAQ' ---> Performance.
* Move 'Customizing s6 behaviour' closer to the top of page.
* Rename 'Customizing s6 behaviour' --> 'Config'
* Generate a TOC with the `doctoc` node.js helper program.

**Comment by glerchundi** [comment]
@dreamcat4, I've updated the README with a TOC, generated by doctoc cleaned by me :-). Also, I renamed FAQ -> Performance. Regarding to customizing s6 behaviour, I made it consciously because I wanted to be there, at the bottom part of the README. I think a README is just as a starting point and default overlay behaviour is enough for most of the people!

again, thanks for your comments.
