### ISSUE TITLE
permit outputting to stdout/stderr

### ISSUE THREAD

**Issue by glerchundi** [just-containers/s6-overlay-builder#13]
because probably in most cases containers are supervised and logged/rotated already, our overlay should propose the best pattern to redirect everything to stdout/stderr instead of /var/log/s6-uncaught-logs.

@skarnet any ideas? lets discuss this here ;-)

**Comment by jprjr** [comment]
You definitely want to be careful about redirecting "everything" - for example, I've seen a container running nginx that logs all http requests to stdout, which is a terrible idea. 

But, if a user specifies a command to run during `docker run` it should probably log to stdout/stderr, since that's what would happen with the regular base images. 

On March 11, 2015 12:27:34 PM CDT, Gorka Lerchundi Osa <notifications@github.com> wrote:
>because probably in most cases containers are already supervised and
>logged/rotated already, our overlay should propose the best pattern to
>redirect everything to stdout/stderr instead of
>/var/log/s6-uncaught-logs.
>
>@skarnet any ideas? lets discuss this here ;-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay-builder/issues/13

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dreamcat4** [comment]
+1

**Comment by glerchundi** [comment]
of course, we need to encourage people to make use of s6 logging mechanisms, but if we want to provide a base overlay which fits well for a wider variety of use cases, we need to provide a way to handle this kind of situations.

i don't think stdouting access.log's is a good idea, but maybe we have a container which doesn't log anything, and we just want to put in stdout everything s6 itself is printing, for example supervised services errors, init errors, whatever.

another question is which one should be the default setting, output to std* or capture everything inside and output to /var/log/s6-uncaught-logs.

**Comment by dreamcat4** [comment]
On Wed, Mar 11, 2015 at 7:15 PM, Gorka Lerchundi Osa <
notifications@github.com> wrote:


> another question is which one should be the default setting, output to
> std* or capture everything inside and output to /var/log/s6-uncaught-logs.
>
+1 for configurability of logging options.

Really I think the default setting should be same as if no process
supervisor was used at all. So `docker logs <container>` can still work as
it is expect it to. Respect generic and official docker ways. People should
not mandatory be having to learn s6-specific logging features right from
the very beginning using s6.

For s6 chatter output, it might be:

* Enabled with debug / verbosity configuration flags or whatever other way
to config s6 e.g. and `ENV` var or `RUN touch /some/file` from within in
Dockerfile.
* Always written to a standard location within the container
`/var/something`.
* Mixed in together with the program's regular stout / std err stream.
* Replace the program's regular stout / std err stream entirely.

So we can see logging configuration gets complex very quickly.

* Default should be s6 fairly silent on std err / std out. Maybe apart from:
  * 1 or 2 lines at very beginning. Just to say at the beginning: "Here I
am, s6 is launched and starting these things".
  * 1 or 2 lines at very end. Just to say "Cleaning up. Reaping zombies,
etc. Bye Bye"
  * A Critical error(s) occur during operation. That is out of s6 regular
control. And not recoverable. e.g. like BSOD condition(s).

Yet another kind of stout / stderr configuration:

* How to mark a run script (managed process that is not from the argv[]) to
be sent / mixed in to stout / std err.
* That is a configuration setting, which is somehow connected to the folder
where the run script is placed in.
* Could be more than 1 managed tasks redicteded (mixed in to) the stout /
std err ?
  * e.g. For example nginx + cron.

Sorry if that all seems pretty complex. It is a lot of possible situations
to consider, when multiple tasks are all running inside of the same
container.

**Comment by glerchundi** [comment]
please feel free to comment everything about the implementation, or fill a new issue to discuss for example:
- default output
- verbosity levels

@dreamcat4 wait for a nginx load balancer example to start talking about how to redirect things to different places. 

:)
