### ISSUE TITLE
stage1 'fix attrs' output

### ISSUE THREAD

**Issue by dreamcat4** [just-containers/s6-overlay-builder#2]
the `stage1` will always output same stuff about `fix attrs`. Like this:

```sh
$ docker run --tty --name s6test dreamcat4/s6test
[fix-attrs] fixing file attributes (ownership & permission)...
[fix-attrs] /etc/fix-attrs.d/00-base: applying...
[fix-attrs] /etc/fix-attrs.d/00-base: done.
[fix-attrs] done.
```

Might be nice to eventually hide that. Replace it with something else. e.g.;

```sh
s6 starting up...
done
```
Which is useful when using `execline` incurrs some significant startup delay.

Else we could print nothing (be completely silent). Until quit  triggers the reaping (which is always useful to print out).

Or if we could let users set an optional ENV variable. To tell our stage1,2,3 to switch on a full debug output. Not sure if that is possible or might make too complex the script (because it is written in execline).

**Comment by glerchundi** [comment]
I think outputting things is really important to have a fine grained control over what is and what isn't doing your container. Although it would be interesting to have a VERBOSITY like env variable to modify stdout printing levels.

After modifying init-stages we'll see if this fits, ok?

**Comment by dreamcat4** [comment]
Fit attrs output is supressed from v1.7.0+ onwards. And we now have other issue for discussing general debugging output / stdout / stderr etc.
