### ISSUE TITLE
Suggestion: move docs + release tarballs over to new 's6-overlay' project

### ISSUE THREAD

**Issue by dreamcat4** [just-containers/s6-overlay-builder#33]
Hello again!

There is a bit of confusion ATM about where / how to download the `s6-overlay` tarball build product. (end users). It would be helpful to make a fake Github Project to push the documentation + releases section to.

Then the README docs for this `s6-overlay-builder`, (and it's releases page) - can stay focussed on the build tool itself, which regular users to not need to see mixed together, or be confused about.

No big hurry. But it seems like a time to suggest when development has mostly stabalized. We just have to keep working and spit / polish the Documentation John has come up with.

@jprjr Wiki is actually harder to find. It not so obvious as a `README.md` and people don't normally see it very well. I can understand when is already mixed up with builder notes. But I hope we can just move your entire wiki page to be the main `README.md` file on new fake `s6-overlay` project. So people can see it / find it. & Many thanks for already doing a big hefty part of this s6-overlay README documentation. It is now much less daunting to finish off. Just be tweaked a little bit more / missing bits added to / improved incrementally. Appreciate it.

@glerchundi It would make sense to move the tarballs to other fake project soon, before too many other people start using those download URLs.

**Comment by glerchundi** [comment]
Hi!

I agree that wiki is harder to find, I'm going to move what john wrote to the frontpage.

Regarding to move tarballs to another release fake project, I completely disagree. People should look at one place, one place for everything, issues, pending request, and even releases.

Anyway, thanks for your comments, they're really appreciated.

**Comment by dreamcat4** [comment]
> Regarding to move tarballs to another release fake project, I completely disagree. People should look at one place, one place for everything, issues, pending request, and even releases.

OK. Still then why not just rename this existing project `s6-overlay-builder` ---> `s6-overlay`, since it encompasses both things? Still keeping 1 single project (no fake thing).

It will look better, and the download URL is a little piece shorter.

```Dockerfile
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.9.1.0/s6-overlay-linux-amd64.tar.gz /tmp/
```

That is a small change. But it makes sense because much higher % percentage of the users will not be building. Just only using it. And the general shorter name does still generally imply builder part is included.

**Comment by glerchundi** [comment]
Yeah, but this is a commitment between project names and ease to remember overlay project name. We want to create a full set of docker images under `just-containers` umbrella and I need a way (or maybe not :\) to differentiates between docker images and builders themselves (skaware & s6-overlay).

**Comment by dreamcat4** [comment]
@glerchundi

Well I am putting all of my docker images in a single repo called `docker-images`. Because you can point the hub auto builds ('trusted builds') into a subdir. It is working well for me.

https://github.com/dreamcat4/docker-images

Of course I only have 1 image in there ATM. But that is growing soon. My point is - if you do that then they are all obviously docker images. *The other popular convention people use for separate repos* is to prefix `docker-` before the image name. E.g. `docker-redis` or `docker-apache` etc. So then again (if you adopt either of those 2 ways) then adding `-builder` suffix to multiple things would not be necessary.

And/or you might wish rename the organisation from `just-containers` to something else. When it is not only "just containers". But also certain other things in here too. There might be a better name for it perhaps. I don't know. @jprjr might have some better ideas than me about all this. Just something shorter to keep the URL small I rekon.

**Comment by dreamcat4** [comment]
@glerchundi 

Example:

```yaml
organisation:
gorka.dkr

repos:
images
s6-overlay
etc
```

so then:

```sh
gorka.dkr/images/base
gorka.dkr/images/2
gorka.dkr/images/3

gorka.dkr/s6-overlay
gorka.dkr/etc
```

**Comment by glerchundi** [comment]
I already did that ([glerchundi/docker-images](https://github.com/glerchundi/docker-images)) and I wouldn't recommend it because issues, pull requests and even release tags will mix and mess everything. We created `just-containers` to create containers, so all projects included in it are by-default containers. Although I know that the de-facto convention is to prepend `docker-` to images, this doesn't apply to us because the organization name itself already defines what we do :-)
I think we need to keep "docker" container names clean, for example, `nginx-loadbalancer` and in concrete cases like these ones decide how to handle naming. We can do one of the following:
* keep as it is right now
* remove `-builder` from s6-overlay and skaware.

What do you think @jprjr?

**Comment by dreamcat4** [comment]
On Fri, Apr 10, 2015 at 1:50 PM, Gorka Lerchundi Osa <
notifications@github.com> wrote:

> I already did that (glerchundi/docker-images
> <https://github.com/glerchundi/docker-images>) and I wouldn't recommend
> it because issues, pull requests and even release tags will mix and mess
> everything.
>
Thanks for mentioning that downside. Actually I make tags like
`pipework-1.04` to avoid that tags problem. And don't auto-build the
`master` as `latest`.

We created just-containers to create containers, so all projects included
> in it are by-default containers. Although I know that the de-facto
> convention is to prepend docker- to images, this doesn't apply to us
> because the organization name itself already defines what we do :-)
>
Ok :)

**Comment by glerchundi** [comment]
just to let you know that I have created `nginx-loadbalancer` which, i think, it's a full showcase of s6 features :-)

https://github.com/just-containers/nginx-loadbalancer

**Comment by jprjr** [comment]
@glerchundi holy crap. I'm looking at that `nginx-loadbalancer` right now, this is awesome.

**Comment by glerchundi** [comment]
@jprjr thanks! hope it is useful

**Comment by glerchundi** [comment]
@dreamcat4, I agree with you that `-builder` is not a very "marketinian" suffix so I'm going to remove it not before knowing that after a rename access to the old repo name guaranteed! https://github.com/blog/1508-repository-redirects-are-here

**Comment by dreamcat4** [comment]
@glerchundi Thanks! :)

**Comment by glerchundi** [comment]
Suggestions are always welcome!
